### ISSUE TITLE
Homework Week 10

### ISSUE THREAD

**Issue by ptums** [ltdelia/LIRI#1]
Hey Lou, I couldn't run the liri program because it required the keys.js file or at least have the authentication codes to access the twitter API. Can you fix that and re push it to the repo?

Thank you,

Peter

**Comment by ptums** [comment]
Hey Lou no worries about the keys. I know due to security reasons you can't upload your twitter authentication keys to github. I got my own. So now I'll be able to run your program.

**Comment by ptums** [comment]
Just finished. Overall nice job! How do you feel about node.js thus far?

**Comment by ltdelia** [comment]
Thanks Peter! Sorry about not pushing the keys. It was in the homework instructions to list "keys.js" in our .gitignore file.

Overall, I'm feeling pretty great about Node! NPM packages are incredibly useful, and it's great to test .js files.
